# Generated by Django 4.2.8 on 2023-12-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_url', models.CharField(max_length=2048)),
                ('shorted_url', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
            ],
        ),
    ]
