# Generated by Django 4.2.8 on 2023-12-27 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_url', models.CharField(max_length=2048, unique=True)),
                ('shorted_url', models.CharField(max_length=256, unique=True)),
                ('key', models.CharField(max_length=256, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('access_counter', models.IntegerField(default=0)),
            ],
        ),
    ]
