# Generated by Django 4.2.8 on 2023-12-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0002_alter_url_full_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='key',
            field=models.CharField(default='hello', max_length=256, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='url',
            name='shorted_url',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
